swagger: '2.0'
info:
  title: Bank Argent API Documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
          examples:
            application/json:
              token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Invalid Fields - One or more fields are incorrect.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields - One or more fields are missing or incorrect.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch User Profile
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields - The request parameters are incorrect.
        '401':
          description: Unauthorized - Authentication failed.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Profile
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields - The request parameters are incorrect.
        '401':
          description: Unauthorized - Authentication failed.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /user/transaction/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        description: The transaction ID
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Fetch User Transactions
      description: API for fetching transactions for a month
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields - The request parameters are incorrect.
        '401':
          description: Unauthorized - Authentication failed.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update User Transaction
      description: API for updating a transaction with a Note or/and a Category
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: The transaction ID
        - in: body
          name: body
          description: Update user transaction attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionAnnotation'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields - The request parameters are incorrect.
        '401':
          description: Unauthorized - Authentication failed.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
      userName:
        type: string
        description: User public name

  Login:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        format: date
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Account balance after transaction
      transactionType:
        type: string
        description: Type of transaction (e.g., electronic, cheque)
      category:
        type: string
        description: Category of the transaction (e.g., food). Can be modified.
      note:
        type: string
        description: Note for the transaction, empty by default. Can be modified.

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
        description: "List of banking transactions carried out during the month. Each element is an object and represents a transaction."

  TransactionAnnotation:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
      note:
        type: string
    required:
      - id
    description: "The category and note fields are optional. Only those present in the body will be modified on the server. The id is the id of the transaction to modify."
